name: Go

on:
  push:
    paths:
      - ".github/workflows/go-test.yml"
      - "server/**"

jobs:
  run-tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.16

      - name: Build
        run: |
          cd ./server
          go build -v ./...

      - name: Test
        run: |
          cd ./server
          go test -v ./...
